const assert=require('node:assert/strict'),slip=require('../packing-slip.js');
const pages=require('./fixtures/shopee-packing-batch.json');
const packing=pages.flatMap(slip.extractPackingSections);
assert.deepEqual(packing.map(p=>p.orderId),['250101TEST0006','250101TEST0005','250101TEST0004','250101TEST0003']);
assert.deepEqual(packing.map(p=>p.rows.length),[3,1,2,2]);
assert.ok(packing.every(p=>p.buyerNote===''));
assert.deepEqual(packing[0].rows[1],{sku:'PT11',spec:'藏青色 / L',qty:1});
const top=pages[0].filter(i=>i.transform[5]>500);
assert.deepEqual(slip.extractPackingSections(top),[packing[0]]);
assert.throws(()=>slip.extractPackingSections(top.filter(i=>i.str!=='PT11_NVY_L')),/第 2 列.*不完整/);
assert.throws(()=>slip.extractPackingSections(top.filter(i=>!(i.transform[4]>480 && i.transform[4]<500 && i.str==='1'))),/不完整/);
const ids=packing.map(p=>p.orderId).reverse();
assert.deepEqual(slip.matchPackingToLabels(packing,ids),[...packing].reverse());
assert.throws(()=>slip.matchPackingToLabels(packing,ids.slice(1)),/訂單數不同/);
assert.throws(()=>slip.matchPackingToLabels(packing,[ids[0],ids[0],ids[2],ids[3]]),/重複/);
assert.throws(()=>slip.matchPackingToLabels(packing,['',...ids.slice(1)]),/無法唯一/);
assert.throws(()=>slip.matchPackingToLabels([packing[0],packing[0]],[packing[0].orderId,packing[0].orderId]),/無法唯一/);
assert.deepEqual(slip.matchPackingToLabels([packing[0]],['']),[packing[0]]);
console.log('PASS: real four-order/two-page packing, single order with missing parent SKU, 8 items, empty notes, reordered matching, missing data/ambiguous matching rejection');
