const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const {pathToFileURL}=require('node:url');
const PDFLib=require('../node_modules/pdf-lib');
const fontkit=require('../vendor/fontkit.umd.min.js');
const slip=require('../packing-slip.js');
const item=(str,x,y)=>({str,transform:[12,0,0,12,x,y],height:12});
const headers=[item('#',20,750),item('主商品貨號',55,750),item('商品名稱',180,750),item('商品規格',370,750),item('數量',540,750)];
const expected=[{sku:'TS13',variantSku:'',name:'完整商品名稱測試',spec:'藏青色 / L',qty:2},{sku:'PT03',variantSku:'',name:'完整商品名稱測試',spec:'深棕色 / M',qty:1},{sku:'KN01',variantSku:'',name:'完整商品名稱測試',spec:'燕麥色 / XL',qty:3}];
const items=[...headers];
expected.forEach((r,i)=>{const y=700-i*80;items.push(item(String(i+1),20,y),item(r.sku,55,y),item('完整商品名稱測試',180,y),item(r.spec,370,y),item(String(r.qty),540,y));});
items.push(item('買家備註：不要印出',20,400));
assert.deepEqual(slip.extractRows(items),expected);
const withVariant=[...items,item('商品選項貨號',280,750),item('TS13_NVY_L',280,700),item('PT03_BRN_M',280,620),item('KN01_OAT_XL',280,540)];
const variantExpected=expected.map((r,i)=>({...r,variantSku:['TS13_NVY_L','PT03_BRN_M','KN01_OAT_XL'][i]}));
assert.deepEqual(slip.extractRows(withVariant),variantExpected);
const wrappedVariant=withVariant.filter(i=>i.str!=='TS13_NVY_L');wrappedVariant.push(item('TS13_',280,700),item('NVY_L',280,680));
assert.deepEqual(slip.extractRows(wrappedVariant),variantExpected);
assert.throws(()=>slip.extractRows(items.filter(i=>i.str!=='數量')),/無法辨識/);
assert.throws(()=>slip.extractRows(items.filter(i=>!(i.transform[4]===540 && i.transform[5]===700))),/不完整/);
const wrapped=items.filter(i=>!(i.transform[4]===370 && i.transform[5]===700));wrapped.push(item('藏青色',370,700),item('/ L',370,680));
assert.equal(slip.extractRows(wrapped)[0].spec,'藏青色 / L');
assert.throws(()=>slip.extractRows([...items,item('abc',545,685)]),/不完整/);
const noIndex=items.filter(i=>i.transform[4]!==20 || !/^([#]|[1-3])$/.test(i.str));
assert.deepEqual(slip.extractRows(noIndex),expected);
const aliases=items.map(i=>({...i,str:i.str==='商品規格'?'商品選項':i.str==='數量'?'購買數量':i.str}));
assert.deepEqual(slip.extractRows(aliases),expected);
const multiline=items.filter(i=>i.str!=='商品規格');multiline.push(item('商品',370,750),item('規格',370,737));
assert.deepEqual(slip.extractRows(multiline),expected);
const fullwidth=items.map(i=>({...i,str:i.str==='2'?'２':i.str}));
assert.deepEqual(slip.extractRows(fullwidth),expected);
(async()=>{
  const dir=path.resolve(__dirname,'../tmp/pdfs');fs.mkdirSync(dir,{recursive:true});
  const fontBytes=fs.readFileSync(path.resolve(__dirname,'../vendor/NotoSansTC.ttf'));
  const source=await PDFLib.PDFDocument.create();source.registerFontkit(fontkit);
  const sourceFont=await source.embedFont(fontBytes,{subset:false});
  const ascii=await source.embedFont(PDFLib.StandardFonts.Helvetica);
  const sourcePage=source.addPage([595.28,841.89]);
  items.forEach(i=>sourcePage.drawText(i.str,{x:i.transform[4],y:i.transform[5],size:12,font:/^[\x20-\x7e]+$/.test(i.str)?ascii:sourceFont}));
  const bytes=await source.save();
  const pdfjs=await import(pathToFileURL(path.resolve(__dirname,'../vendor/pdf.min.mjs')).href);
  pdfjs.GlobalWorkerOptions.workerSrc=pathToFileURL(path.resolve(__dirname,'../vendor/pdf.worker.min.mjs')).href;
  const parsed=await slip.readPacking(bytes.buffer.slice(bytes.byteOffset,bytes.byteOffset+bytes.byteLength),pdfjs);
  assert.deepEqual(parsed,[{rows:expected,buyerNote:'不要印出',orderId:''}]);
  const out=await PDFLib.PDFDocument.create();out.registerFontkit(fontkit);
  const font=await out.embedFont(fontBytes,{subset:false});const numberFont=await out.embedFont(PDFLib.StandardFonts.CourierBold);
  await slip.appendRows(out,variantExpected,{font,numberFont},PDFLib,parsed[0].buyerNote);
  const output=await out.save();fs.writeFileSync(path.join(dir,'packing-three-columns.pdf'),output);
  const read=await pdfjs.getDocument({data:output.slice(),isEvalSupported:false}).promise;
  const text=(await (await read.getPage(1)).getTextContent()).items.map(i=>i.str).join(' ');
  for (const key of ['貨號','商品選項','規格','數量','TS13_NVY_L','PT03_BRN_M','KN01_OAT_XL','藏青色']) assert.ok(text.includes(key),key);
  const positions=(await (await read.getPage(1)).getTextContent()).items;
  const titleItems=positions.filter(i=>i.str==='完整商品名稱測試');
  const skuItems=positions.filter(i=>['TS13','PT03','KN01'].includes(i.str));
  for(let i=0;i<3;i++) {
    assert.ok(titleItems[i].transform[5]<skuItems[i].transform[5]);
    assert.ok(Math.abs(titleItems[i].transform[4]-skuItems[i].transform[4])<.01);
    assert.ok(titleItems[i].height<skuItems[i].height);
    if(i<2)assert.ok(titleItems[i].transform[5]>skuItems[i+1].transform[5]);
  }
  assert.ok(text.includes('完整商品名稱測試'));assert.equal((text.match(/完整商品名稱測試/g)||[]).length,3);assert.ok(text.includes('買家備註'));assert.ok(text.includes('不要印出'));await read.loadingTask.destroy();
  // Long full-width titles must survive continuation pages without truncation.
  const longName='長商品名稱含材質剪裁與穿搭說明'.repeat(120);
  const titles=await PDFLib.PDFDocument.create();titles.registerFontkit(fontkit);
  const tf=await titles.embedFont(fontBytes,{subset:false}),tn=await titles.embedFont(PDFLib.StandardFonts.CourierBold);
  await slip.appendRows(titles,[{sku:'TS13',variantSku:'TS13_NVY_L',name:longName,spec:'藏青色 / L',qty:1}],{font:tf,numberFont:tn},PDFLib);
  assert.ok(titles.getPageCount()>1);
  const td=await pdfjs.getDocument({data:await titles.save(),isEvalSupported:false}).promise;
  let titleText='';for(let n=1;n<=td.numPages;n++)titleText+=(await(await td.getPage(n)).getTextContent()).items.filter(i=>! /商品名稱[（(]續[）)]/.test(i.str)).map(i=>i.str).join('');
  titleText=titleText.replace(/商品名稱[（(]續[）)]/g,'').replace(/\s/g,'');assert.ok(titleText.includes(longName));await td.loadingTask.destroy();
  // Check pagination and long specifications do not disappear.
  const multi=await PDFLib.PDFDocument.create();multi.registerFontkit(fontkit);
  const mf=await multi.embedFont(fontBytes,{subset:false});const mn=await multi.embedFont(PDFLib.StandardFonts.CourierBold);
  await slip.appendRows(multi,Array.from({length:20},(_,i)=>({sku:'TS'+String(i+1).padStart(2,'0'),spec:'深棕色 / 加大尺寸 XL / 長規格換行測試',qty:i+1})),{font:mf,numberFont:mn},PDFLib);
  assert.ok(multi.getPageCount()>1);
  const md=await pdfjs.getDocument({data:await multi.save(),isEvalSupported:false}).promise;
  let mt='';for(let i=1;i<=md.numPages;i++)mt+=(await(await md.getPage(i)).getTextContent()).items.map(i=>i.str).join(' ');
  for(let i=1;i<=20;i++)assert.ok(mt.includes('TS'+String(i).padStart(2,'0')));await md.loadingTask.destroy();
  const preview=await PDFLib.PDFDocument.create();const saved=await PDFLib.PDFDocument.load(output);
  const embedded=await preview.embedPage(saved.getPage(0));const p=preview.addPage(slip.PAPER);
  p.drawPage(embedded,{x:-slip.PAPER[0]*.125,y:-slip.PAPER[1]*.125,width:slip.PAPER[0]*1.25,height:slip.PAPER[1]*1.25});
  fs.writeFileSync(path.join(dir,'packing-three-columns-125.pdf'),await preview.save());
  console.log('PASS: column extraction, missing/invalid quantity rejection, wrapped specs, real PDF text extraction, four-column output, 20-row pagination, 125% preview');
})().catch(e=>{console.error(e);process.exitCode=1;});
